myprofile_app/urls.py
from django.urls import path
from .views import(create_recipe, 
                    read_one_recipe, delete_recipe, 
                    update_recipe, my_profile, category_recipes
                )

urlpatterns = [
    path('create_recipe/', create_recipe, name='create_recipe'),
    path('read_one_recipe/<int:pk>/', read_one_recipe, name='read_one_recipe'),
    path('delete_recipe/<int:id>/', delete_recipe, name='delete_recipe'),
    path('update_recipe/<int:id>/', update_recipe, name='update_recipe'),
    path('category_recipes/<int:pk>', category_recipes, name='category_recipes'),
    path('my_profile', my_profile, name='my_profile'),
]

user_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import Register

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', Register.as_view(), name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)

web_culinary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import list_category
# from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', list_category, name="home"),
    path('user/', include('user_app.urls')),
    path('myprofile/', include('myprofile_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)

myprofile_app/models.py
from django.db import models
from user_app.models import UserAuth


class Category(models.Model):
    name_category = models.CharField(max_length=50)

class Recipe(models.Model):
    img_recipe = models.ImageField(upload_to='img_recipe')
    name_recipe = models.CharField(max_length=50)
    description = models.TextField()
    ingredients = models.TextField()
    cooking_process = models.TextField()
    date_add = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(UserAuth, on_delete=models.CASCADE)

user_app/models.py
from django.db import models


from django.contrib.auth.models import AbstractUser

class UserAuth(AbstractUser):
    city = models.CharField(max_length=50)

myprofile_app/forms.py
from django import forms
from django.db.models.base import Model
from .models import Category, Recipe


class MyChoiceCategory(forms.ModelChoiceField):
    def label_from_instance(self, obj: Model) -> str:
        return super().label_from_instance(obj.name_category)

class FormRecipe(forms.ModelForm):
    category = MyChoiceCategory(queryset=Category.objects.all(), empty_label=None)

    class Meta:
        model = Recipe
        exclude = ['user']
        widgets = {
            'name_recipe': forms.Textarea,
            'description': forms.Textarea, 
            'ingredients': forms.Textarea,
        }

class FormRecipeUpdate(forms.ModelForm):

    category = MyChoiceCategory(queryset=Category.objects.all())
    class Meta:
        model = Recipe
        exclude = ['user']
        widgets = {
            'name_recipe': forms.Textarea,
            'description': forms.Textarea, 
            'ingredients': forms.Textarea,
        }

user_app/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserCreationForm(UserCreationForm):
    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={'autocomplete': 'email'})
    )
    city = forms.CharField(
        label=_("Родной город"),
        max_length=100,
        widget=forms.TextInput()
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email", "city")

        

myprofile_app/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Recipe, Category
from .forms import FormRecipe, FormRecipeUpdate 
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required 
from django.core.paginator import Paginator


@login_required
def create_recipe(request):
    if request.method == 'POST':
        form = FormRecipe(request.POST or None, request.FILES)
        if form.is_valid():
            img_recipe = form.cleaned_data['img_recipe']
            name_recipe = form.cleaned_data['name_recipe']
            description = form.cleaned_data['description']
            ingredients = form.cleaned_data['ingredients']
            cooking_process = form.cleaned_data['cooking_process']
            category = form.cleaned_data['category']

            fs = FileSystemStorage()
            filename = fs.save(img_recipe.name, img_recipe)
            recipe = Recipe(img_recipe = filename,
                            name_recipe = name_recipe,
                            description = description,
                            ingredients = ingredients,
                            cooking_process = cooking_process,
                            user = request.user,
                            category = category)
            recipe.save()
            return redirect ('my_profile')
    else:
        form = FormRecipe()
    return render (request, 'myprofile/create_recipe.html', {'form': form})

def category_recipes(request, pk):
    category_list = Category.objects.all()
    category = Category.objects.get(pk=pk)
    recipes = Recipe.objects.filter(category = pk)
    current_page = Paginator(recipes, 4)
    page_number = request.GET.get("page")
    page_obj = current_page.get_page(page_number)
    context = {
            'recipes': recipes, 
            'category_list': category_list,
            'category': category,
            "page_obj": page_obj,
    }
    return render (request, 'maincontent/category_recipes.html', context)

def read_one_recipe(request, pk):
    recipe = get_object_or_404(Recipe, pk = int(pk))
    return render (request, 'myprofile/read_one_recipe.html', {'recipe': recipe})

def my_profile(request):
    user = request.user
    recipe_all = Recipe.objects.filter(user = user)
    current_page = Paginator(recipe_all, 4)
    page_number = request.GET.get("page")
    page_obj = current_page.get_page(page_number)
    context = {
                'user': user, 
                'recipe_all': recipe_all, 
                "page_obj": page_obj
    }
    return render (request, 'myprofile/my_profile.html', context)

def delete_recipe(request, id):
    recipe = get_object_or_404(Recipe, pk = id)
    if recipe is not None:
        recipe.delete()
    return redirect ('my_profile')

def update_recipe(request, id):
    get_recipe = get_object_or_404(Recipe, pk=id)
    if request.method == 'POST':
        form = FormRecipeUpdate(request.POST or None, request.FILES, instance=get_recipe)
        if form.is_valid():
            form.save()
            return redirect ('my_profile')
    else:
        form = FormRecipeUpdate(instance=get_recipe)
    return render (request, 'myprofile/update_recipe.html', {'form': form})

user_app/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from django.views import View
from .forms import UserCreationForm

class Register(View):
    template_name = 'registration/register.html'
    template_home = 'home.html'

    def get(self, request):
        context = {
            'form': UserCreationForm()
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password) # автоматич авторизация
            login(request, user)
            return render(request, self.template_home)
        context = {
            'form': form
        }
        return render(request, self.template_name, context)

web_culinary/views.py
from django.shortcuts import render
from myprofile_app.models import Category, Recipe


def list_category(request):
    for_recipe =  Recipe.objects.order_by('?')[:4]
    category_list = Category.objects.all()
    return render (request, 'home.html', {'for_recipe': for_recipe, 'category_list': category_list})

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block main__title %}
    <title>base_templates</title>
    {% endblock %}
    
    {% load static %}
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}"  rel="stylesheet" >
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</head>
<body>

  <nav class="navbar navbar-expand-lg d-flex justify-content-between" style="background-color: rgba(230, 240, 170, 1);" max-width="600px">
    <div class="container">
      <div class="navbar-collapse">
          <nav class="navbar navbar-light">
              <a class="navbar-brand" href="{% url 'home' %}">
                  <img src="{% static 'image/main_icon.png' %}" alt="logo" width="70" height="64">
                  <b>Сайт рецептов</b>
              </a>
          </nav>
        {% block category %}
        {% endblock %}
      </div>
      <div class="navbar">
            {% if user.is_authenticated %}
            <nav class="navbar">
              <form action="{% url 'my_profile' %}" class="inline">
                <button class="btn btn-outline-success me-2" type="button ">Мой профиль</button>
              </form>
              <form action="{% url 'logout' %}" class="inline">
                <button class="btn btn-outline-success me-2" type="button ">Выход</button>
              </form>
            </nav>
            {% else %}
            <nav class="navbar">
              <form action="{% url 'register' %}" class="inline">
                <button class="btn btn-outline-success me-2" type="button ">Регистрация</button>
              </form>
              <form action="{% url 'login' %}" class="inline">
                <button class="btn btn-outline-success me-2" type="button ">Авторизация</button>
              </form>
            </nav>
            {% endif %}
      </div>
    </div>
  </nav>
  {% block title %}
  {% endblock %}

  {% block subtitle %}
  {% endblock %}

  {% block content %}
  {% endblock %}


</body>
</html>

templates/home.html
{% extends 'base.html'%}

{% block main__title %}
<title>Домашняя страница</title>
{% endblock %}

{% block category %}
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle me-2" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Категории рецептов
    </button>
    <ul class="dropdown-menu">
      {% for category in category_list %}
        <li><a class="dropdown-item" href="{% url 'category_recipes' category.pk %}">{{ category.name_category }}</a></li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}


{% block title %}
  <center>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          {% if user.is_authenticated %}
            <p><h5 class="fw-light"><b>Здраствуйте {{ user }} </h5></p>
          {% endif %}

          <b></b><h1 class="fw-light"><b>Сайт рецептов</b></h1></b>

        </div>
      </div>
    </section>
  </center>
{% endblock %}


{% block subtitle %}
  <section class="text-center container">
    <h1 class="fw-light">4 случайных блюда:</h1>
    <h1>
      {% for category in list_category %}
        {{ category }}
      {% endfor %}
    </h1>
      <a href="{% url 'home' %}" class="btn btn-primary my-2">Обновить рецепты</a>
  </section>
{% endblock %}


{% block content %}
{% for item in for_recipe %}
<center>
  <div class="album py-5 bg-light" style="max-width: 600px;">
    <div class="container">
      <div class="row align-items-center">
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ item.img_recipe.url }}" alt="img_recipe">
            <div class="card-body">
              <b><p class="card-text">{{ item.name_recipe|linebreaks }}</p></b>
              <p class="card-text">{{ item.description|linebreaks }}</p>
              <div>
                <form action="{% url 'read_one_recipe' item.pk %}" class="inline">
                  <button type="button " class="btn btn-sm btn-outline-secondary">Посмотреть рецепт</button>
                </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</center>
{% endfor %}
{% endblock %}

templates/maincontent/category_recipes.html
{% extends 'base.html'%}

{% block main__title %}
<title>Категория</title>
{% endblock %}

{% block category %}
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle me-2" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Категории рецептов
  </button>
  <ul class="dropdown-menu">
    {% for category in category_list %}
      <li><a class="dropdown-item" href="{% url 'category_recipes' category.pk %}">{{ category.name_category }}</a></li>
    {% endfor %}
  </ul>
</div>
{% endblock %}


{% block title %}
<center>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light"><b>Категории рецептов</b></h1>
        <b></b><h1 class="fw-light"><b><u>{{ category.name_category }}</u></b></h1></b>
      </div>
    </div>
  </section>
</center>
{% endblock %}

{% block subtitle %}
{% endblock %}

{% block content %}
{% for item in page_obj %}
<center>
  <div class="album py-5 bg-light" style="max-width: 600px;">
    <div class="container">
      <div class="row align-items-center">
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ item.img_recipe.url }}" alt="img_recipe">
            <div class="card-body">
              <b><p class="card-text">{{ item.name_recipe|linebreaks }}</p></b>
              <p class="card-text">{{ item.description|linebreaks }}</p>
              <div>
                <div class="btn-group">
                  <center>
                    <form action="{% url 'read_one_recipe' item.pk %}" class="inline">
                      <button type="button " class="btn btn-sm btn-outline-secondary">Посмотреть рецепт</button>
                    </form>
                </center>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</center>
<hr>
{% endfor %}
<center>
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page=1/">&laquo; Первая</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
    {% endif %}
    </li>
    {% for page in page_obj.paginator.page_range %}
      {% if page == page_obj.number %}
        <li class="page-item active"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
      {% else %}
        <li><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
    </li>
    <li class="page-item"></li>
      <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
    </li>
    {% endif %}
  </ul>
  </span>
</center>


{% endblock %}

templates/myprofile/create_recipe.html
{% extends 'base.html'%}

{% block main__title %}
    <title>Создание рецепта</title>
{% endblock %}

{% block category %}
{% endblock %}

{% block title %}
    <center>
        <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
            <b></b><h2 class="fw-light"><b>Заполните поля для добавления рецепта</b></h2></b>
            </div>
        </div>
        <hr>
        </section>
    </center>
{% endblock %}

{% block content %}
    <center>
        <form method="post" enctype="multipart/form-data">
            <table>
                {% csrf_token %}
                <div class="col-md-6">
                    <tr>
                        <td>
                            <label for="formFile" class="form-label">Выберите изображение</label>
                        </td>
                        <td>
                            <h4><pre>    </pre></h4>
                        </td>
                        <td>
                            {{ form.img_recipe }}
                        </td>
                    </tr>
                </div>
                <div class="col-md-6">
                    <tr>
                        <td>
                            <label for="exampleFormControlTextarea1" class="form-label">Наименвание блюда</label>
                        </td>
                        <td>
                            <h4><pre>    </pre></h4>
                        </td>
                        <td>
                            {{ form.name_recipe }}
                        </td>
                    </tr>
                </div>

                <div class="col-md-6">
                    <tr>
                        <td>
                            <label for="exampleFormControlTextarea1" class="form-label">Описание блюда</label>
                        </td>
                        <td>
                            <h4><pre>    </pre></h4>
                        </td>
                        <td>
                            {{ form.description }}>
                        </td>
                    </tr>
                </div>

                <div class="col-md-6">
                    <tr>
                        <td>
                            <label for="exampleFormControlTextarea1" class="form-label">Ингридиенты</label>
                        </td>
                        <td>
                            <h4><pre>    </pre></h4>
                        </td>
                        <td>
                            {{ form.ingredients }}
                        </td>
                    </tr>
                </div>

                <div class="col-md-6">
                    <tr>
                        <td>
                            <label for="exampleFormControlTextarea1" class="form-label">Процесс приготовления</label>
                        </td>
                        <td>
                            <h4><pre>    </pre></h4>
                        </td>
                        <td>
                            {{ form.cooking_process }}
                        </td>
                    </tr>
                </div>

                <div class="col-md-6">
                    <tr>
                        <td>
                            <label for="id_category" class="form-label">Выберите Категорию</label>
                        </td>
                        <td>
                            <h4><pre>    </pre></h4>
                        </td>
                        <td>
                            {{ form.category }}
                        </td>
                    </tr>
                </div>


            </table>
                <hr>
                <button type="submit" class="btn btn-success">
                    Сохранить рецепт и вернуться в свой профиль
                </button>

        </form>
    </center>
{% endblock %}

templates/myprofile/my_profile.html
{% extends 'base.html'%}

{% block main__title %}
<title>Мой профиль</title>
{% endblock %}

{% block category %}
{% endblock %}

{% block title %}
  <center>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light"><b>Привет {{ user }}</b></h1>
          <h3 class="fw-light">Здесь отображены информация о вас и список ваших рецептов</h3>
        </div>
      </div>
    </section>
  </center>
{% endblock %}

{% block subtitle %}
  <center>
    <h1 class="fw-light">
      <b>
        Информация о пользователе
      </b>
    </h1>
  </center>
  <hr>
  <center>
    <table>
        <div class="col-md-6">
          <tr>
            <td>
              <h4>Ваше имя</h4>
            </td>
            <td>
                <h4><pre>  -  </pre></h4>
               </td>
              <td>
                <h4>{{ user.username }}</h4>
               </td>
          </tr>
        </div>
        <div class="col-md-6">
          <tr>
               <td>
                <h4>Ваш Email</h4>
              </td>
              <td>
                <h4><pre>  -  </pre></h4>
              </td>
              <td>
                 <h4>{{ user.email }}</h4>
               </td>
           </tr>
        </div>
        <div class="col-md-6">
          <tr>
              <td>
                <h4>Ваш город</h4>
              </td>
              <td>
                <h4><pre>  -  </pre></h4>
              </td>
              <td>
                <h4>{{ user.city }}</h4>
              </td>
          </tr>
      </div>
    </table>
  </center>
  <hr>
{% endblock %}

{% block content %}
<center>
  <a href="{% url 'create_recipe' %}" class="btn btn-primary">Добавить новый рецепт</a>
  <hr>
  <h1 class="fw-light">
    <b>
      Список рецептов
    </b>
  </h1>
</center>
{% for item in page_obj %}
<center>
<div class="container">
  <div class="album py-5 bg-light" style="max-width: 600px;">
    <div class="container">
      <div class="row align-items-center">
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ item.img_recipe.url }}" alt="img_recipe">
            <div class="card-body">
              <b><p class="card-text">{{ item.name_recipe|linebreaks }}</p></b>
              <p class="card-text">{{ item.description|linebreaks }}</p>
              <div>
                <div class="btn-group">
                    <form action="{% url 'read_one_recipe' item.pk %}" class="inline">
                      <button type="button " class="btn btn-sm btn-outline-secondary">Посмотреть рецепт</button>
                    </form>
                    <form action="{% url 'update_recipe' item.pk %}" class="inline">
                      <button type="button " class="btn btn-sm btn-outline-secondary">Редактировать рецепт</button>
                    </form>
                    <form action="{% url 'delete_recipe' item.pk %}" class="inline">
                      <button type="button " class="btn btn-sm btn-outline-secondary">Удалить рецепт</button>
                    </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endfor %}
</center>
<ul class="pagination justify-content-center">
  {% if page_obj.has_previous %}
  <li class="page-item">
    <a class="page-link" href="?page=1/">&laquo; Первая</a>
  </li>
  <li class="page-item">
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
  {% endif %}
  </li>
  {% for page in page_obj.paginator.page_range %}
    {% if page == page_obj.number %}
      <li class="page-item active"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
    {% else %}
      <li><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
    {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
  <li class="page-item">
    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
  </li>
  <li class="page-item"></li>
    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
  </li>
  {% endif %}
</ul>
{% endblock %}

templates/myprofile/read_one_recipe.html
{% extends 'base.html'%}

{% block main__title %}
<title>Рецепт</title>
{% endblock %}

{% block category %}
{% endblock %}

{% block title %}
  <center>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light"><b>Рецепт</b></h1>
          <h2 class="fw-light">{{ recipe.name_recipe|linebreaks }}</h1>
          <h2 class="fw-light">автор блюда "{{ recipe.user }}"</h1>
          
        </div>
      </div>
    </section>
  </center>
{% endblock %}

{% block subtitle %}

<center>
    <div class="album py-5 bg-light" style="max-width: 600px;">
      <div class="container">
        <div class="row align-items-center">
          <div class="col">
            <div class="card shadow-sm">
              <img src="{{ recipe.img_recipe.url }}" alt="img_recipe">
              <div class="card-body">
                <b><p class="card-text">Категория блюда:</p></b>
                <p class="card-text">{{ recipe.category.name_category|linebreaks }}</p>
                <b><p class="card-text">Описание блюда:</p></b>
                <p class="card-text">{{ recipe.description|linebreaks }}</p>
                <b><p class="card-text">Ингридиенты:</p></b>
                <p class="card-text">{{ recipe.ingredients|linebreaks }}</p>
                <b><p class="card-text">Ход приготовления</p></b>
                <p class="card-text">{{ recipe.cooking_process|linebreaks }}</p>
                <div>
                  <form action="{% url 'home' %}" class="inline">
                    <button type="button " class="btn btn-sm btn-outline-secondary">Вернуться на главную</button>
                  </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </center>
{% endblock %}

templates/myprofile/update_recipe.html
{% extends 'base.html'%}

{% block main__title %}
<title>Создание рецепта</title>
{% endblock %}

{% block category %}
{% endblock %}


{% block title %}
  <center>
    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <b></b><h2 class="fw-light"><b>Измените необходимые поля выбранного рецепта</b></h2></b>
        </div>
      </div>
      <hr>
    </section>
  </center>
{% endblock %}

{% block content %}
<center>
    <form method="post" enctype="multipart/form-data">
        <table>
            {% csrf_token %}
            <div class="col-md-6">
                <tr>
                    <td>
                        <label for="formFile" class="form-label">Выберите картинку</label>
                    </td>
                    <td>
                        <h4><pre>    </pre></h4>
                    </td>
                    <td>
                        {{ form.img_recipe }}
                    </td>
                </tr>
            </div>
            <div class="col-md-6">
                <tr>
                    <td>
                        <label for="exampleFormControlTextarea1" class="form-label">Название блюда</label>
                    </td>
                    <td>
                        <h4><pre>    </pre></h4>
                    </td>
                    <td>
                        {{ form.name_recipe }}
                    </td>
                </tr>
            </div>

            <div class="col-md-6">
                <tr>
                    <td>
                        <label for="exampleFormControlTextarea1" class="form-label">Описание блюда</label>
                    </td>
                    <td>
                        <h4><pre>    </pre></h4>
                    </td>
                    <td>
                        {{ form.description }}>
                    </td>
                </tr>
            </div>

            <div class="col-md-6">
                <tr>
                    <td>
                        <label for="exampleFormControlTextarea1" class="form-label">Ингридиенты</label>
                    </td>
                    <td>
                        <h4><pre>    </pre></h4>
                    </td>
                    <td>
                        {{ form.ingredients }}
                    </td>
                </tr>
            </div>

            <div class="col-md-6">
                <tr>
                    <td>
                        <label for="exampleFormControlTextarea1" class="form-label">Процесс приготовления</label>
                    </td>
                    <td>
                        <h4><pre>    </pre></h4>
                    </td>
                    <td>
                        {{ form.cooking_process }}
                    </td>
                </tr>
            </div>

            <div class="col-md-6">
                <tr>
                    <td>
                        <label for="id_category" class="form-label">Выберите Категорию</label>
                    </td>
                    <td>
                        <h4><pre>    </pre></h4>
                    </td>
                    <td>
                        {{ form.category }}
                    </td>
                </tr>
            </div>


        </table>
            <hr>
            <button type="submit" class="btn btn-success">
                Сохранить рецепт и вернуться в свой профиль
            </button>

    </form>
</center>


{% endblock %}